### PR TITLE
Health record

### PR DESCRIPTION
**Pull request by stavros-0**
- Two interview were used to fill out the Department of Health Vermont Record of Divorce or Annulment and Department of Health Vermont Record of Civil Union Dissolution or Annulment

### CODE REVIEW

**Review by miabonardi — CHANGES_REQUESTED** [review]
Lots of great work here. 

A few things need to be updated before merging:

1. Update the kickout language to how it is on main branch for both kids and no kids yml files: 

```
  if not plaintiff_VT and not defendant_VT:
  
    if not marriage_or_civil_union_VT:
    
      jurisdiction_kickout
```

2. The PDF for marriage is missing. 
3. These templates should show up based on whether there is a marriage, civil union/annulment. You can review how to do this by looking at https://suffolklitlab.org/docassemble-AssemblyLine-documentation/docs/framework/aldocument#enabled-example
4. You can remove the next steps document.

**Comment by nonprofittechy** [comment]
@stavros-0 @VTskier @miabonardi I did a merge to main that seems to have solved merge conflict, but this had some conflicting files. please review manually before merging.

@stavros-0 you'll need to pull this into a new project in your playground environment before making any new changes

**Comment by stavros-0** [comment]
I was able to combine both interview into one. I removed the extra yml files that separated the two documents into two interviews.

**Review by miabonardi — CHANGES_REQUESTED** [review]
Lots of great work here. 

A few things:

1. Please review my edits on this commit [8d328fd](https://github.com/LSVermont/docassemble-VTDivorce/pull/52/commits/8d328fd99b3f85e66719a75b763aa59b6dae95bb). When working on multiform projects and integrating one form into another, it's important to check if any of the variables are already defined by the main interview. For example, the health record asks about the attorneys, but the main interview has already collected this. You just need to sync the variable names. 
2. There is a question that asks for county. It should use the dropdown of VT counties already used for trial court counties. 
3. Add concluding question marks / punctuation to your on-screen written questions.
4. The checkboxes on the form for husband/wife/spouse do not have a question and do not populate

**Review by miabonardi — APPROVED** [review]
Great work!

**Comment by nonprofittechy** [comment]
@stavros-0 can you please resolve the merge conflict here and confirm which version is correct? then I will merge

**Pull request merged**
